### PR TITLE
Tweaks to ParseExpressionList

### LINKED ISSUE #7: ExpressionList can match trailing commas
This is a departure from Lua syntax, where a trailing comma in an expression list is a parse error:

```lua
print(1, 2,)
```

`ParseExpressionList` does not handle this right now; it will parse a trailing comma perfectly fine.

### PR DESCRIPTION
**Pull request by AmaranthineCodices**
Fixes #7.

Also introduces a `token!` macro for creating a token when we don't care about position in the source file or whitespace. Right now this lives in the parser's `test` module - is it worth moving it out?

### CODE REVIEW

File: src/parser.rs [hunk 1]
```diff
@@ -301,25 +301,33 @@ impl<'a> Parser<'a, Vec<Expression<'a>>> for ParseExpressionList {
...
             }
         }
 
-        Ok((state, expressions))
+        if on_comma {
+            Err(ParseAbort::NoMatch)
+        }
+        else {
+            Ok((state, expressions))
+        }
```
Comment (LPGhatguy) [inline src/parser.rs]: There's actually a really handy way to solve this without introducing another piece of state! I use it in the one-or-more variant of this same mini-parser with a couple tweaks.

I think it works. Basically:
1. Try to parse an expression. If it fails, return success with an empty list (or an error in the one-or-more case)
2. Loop:
    1. Parse a comma. If it fails, break the loop.
    1. Parse an expression. If it fails, return an error ("expected expression after comma found X")
3. Return success with all of the expressions

**Comment by LPGhatguy** [comment]
I think I'll actually fix `ExpressionList` itself in another commit (changing those to be combinators instead), but I still want the `token!` macro!

**Comment by AmaranthineCodices** [comment]
Alright - the `token!` macro is now the only thing in this PR.
